myreddit/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('subscriptions/', views.SubscriptionsView.as_view(), name='subscriptions'),
    path('all/', views.AllHomeView.as_view(), name='all_home'),
    
    path('search/', views.Search.as_view(), name='search'),
    
    path('post/<int:pk>/', views.ShowPost.as_view(), name='post'),
    path('post/create/', views.CreatePost.as_view(), name='add_post'),
    
    path('group/<int:pk>/', views.GroupView.as_view(), name='group'),
    path('group/create/', views.GroupCreateView.as_view(), name='create_group'),
    
    path('like_post/<int:pk>/', views.LikePostView, name='like_post'),
    path('like_comm/<int:pk>/', views.LikeCommView, name='like_comm'),
    
    path('group/join/<int:pk>/', views.JoinGroupView, name='join_group'),
    path('group/quit/<int:pk>/', views.QuitGroupView, name='quit_group'),
]

myreddit/myreddit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from myreddit import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myreddit/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('password-change/', views.PasswordChangeUser.as_view(), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneUser.as_view(), name='password_change_done'),
    
    path('password-reset/', views.PasswordResetUser.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneUser.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.PasswordResetConfirmUser.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.PasswordResetCompleteUser.as_view(), name='password_reset_complete'),
    
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
]

myreddit/templates/base.html
{% load static %}
{% load main_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static "images/logo32.png" %}" type="image/x-icon">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <title>{{ title|default:"Страница" }}</title>
</head>
<body class='bg-dark text-white'>
    <!-- navbar -->
    <nav class="navbar bg-dark border-bottom border-body navbar-expand-md px-5 sticky-top" data-bs-theme="dark" id='main-menu'>
        <a href="{% url "home" %}" class='navbar-brand'>
            <img src="{% static "images/logo32.png" %}">
            MyReddit
        </a>
        <!-- toggle button for mobile nav -->
        <button class="navbar-toggler" type='button' data-bs-toggle='collapse' 
        data-bs-target='#main-nav' aria-controls='main-nav' aria-expanded='false'
        aria-label='Toggle navigation'>
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- navbar links -->
            <div class="collapse navbar-collapse justify-content-end align-center" id="main-nav">
                <div class="searchbar">
                    {% searchbar as search %}
                    <form action='{% url "search" %}'>
                        <a class="has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#searcher" aria-expanded="false" aria-controls="searcher">
                            <input autocomplete="off" name='inp' type="search" class="form-control" placeholder="Search">
                        </a>
                        <div id='searcherup'>
                            <ul id="searcher" class="list-unstyled collapse" data-bs-parent="#searcher">
                                {% for i in search %}
                                <li class="s-li"><button name="type" value='{{i.name}}'>{{i.title}}</button></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </form>
                </div>

                <ul class="navbar-nav">
                    <li class="nav-item d-md-none">
                        <a href="{% url "add_post" %}" class="nav-link">Create</a>
                    </li>
                    <li class="nav-item ms-2 d-none d-md-inline hover-shadow">
                        <a href="{% url "add_post" %}" class="nav-link">
                            <img src="{% static "images/create.png" %}">
                            <span>Create</span>
                        </a>
                    </li>

                    <li class="nav-item d-md-none">
                        <a class="nav-link has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#notif" aria-expanded="false" aria-controls="notif">Notifications</a>
                    </li>
                    <li class="nav-item ms-2 d-none d-md-inline hover-shadow notifications">
                        <a class="nav-link has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#notif" aria-expanded="false" aria-controls="notif">
                            <img src="{% static "images/notification.png" %}">
                        </a>
                        <ul id="notif" class="list-unstyled collapse h-100" data-bs-parent="#notif">
                            {% for i in user.notif.all %}
                            <li class="s-li">{{i.text}}</li>
                            {% endfor %}
                        </ul>
                    </li>

                    <li class="nav-item d-md-none">
                        <a href="{% url "users:profile" user.id %}" class="nav-link">Account</a>
                    </li>
                    <li class="nav-item ms-2 d-none d-md-inline hover-shadow">
                        <a href="{% url "users:profile" user.id %}" class="nav-link">
                            <img class='nav-avatar' src="{{ user.avatar.url }}">
                        </a>
                    </li>
                </ul>
            </div>
    </nav>

    <!-- Sidebar -->
    <div class="wrapper">
        <aside id="sidebar" class='expand'>
            {% comment %} <div class="d-flex">
                <buttnon id="toggle-btn" type="button">
                    <img src="{% static "images/home_btn.png" %}">
                </buttnon>
            </div> {% endcomment %}
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a href="{% url "home" %}" class="sidebar-link">
                        <img src="{% static "images/home_btn.png" %}">
                        <span>Home</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url "subscriptions" %}" class="sidebar-link">
                        <img src="{% static "images/subscriptions_btn.png" %}">
                        <span>Subscriptions</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a href="{% url "all_home" %}" class="sidebar-link">
                        <img src="{% static "images/all_btn.png" %}">
                        <span>All</span>
                    </a>
                </li>
                <br><br>
                <li class="sidebar-item" id='communities'>
                    <a href="#" class="sidebar-link has-dropdown collapsed" data-bs-toggle="collapse" data-bs-target="#comm" aria-expanded="false" aria-controls="comm">
                        <img src="{% static "images/home_btn.png" %}">
                        <span>Communities</span>
                    </a>
                    <ul id="comm" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                        <li>Admin:</li>
                        {% for group in user.group.all %}
                        {% include "main/includes/group_mini.html" %}
                        {% endfor %}
                        <li>Member:</li>
                        {% for group in user.member.all %}
                        {% include "main/includes/group_mini.html" %}
                        {% endfor %}
                    </ul>
                </li>
            <div class="sidebar-footer">
                <a href="{% url "users:logout" %}" class="sidebar-link">
                    <img src="{% static "images/logout_btn.png" %}">
                    <span>Logout</span>
                </a>
            </div>
        </aside>
        <!-- main content -->
        <div class="main container-xxl">
            {% block content %}
            <h1> Пока пустая страница </h1>
            {% endblock content %}
        </div>
    </div>


    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "js/script.js" %}"></script>
</body>
</html>

myreddit/templates/login_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static "images/logo32.png" %}" type="image/x-icon">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <title>{{ title|default:"Страница" }}</title>
</head>
<body class='bg-dark text-white'>

    <div class="containter mt-5 pt-5">
        <div class="row">
            <div class="col-4 m-auto text-center">
                <h1> {{ title|default:"Title" }} </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-8 m-auto">
                {% if user.is_authenticated %}
                {% block content_ignore %}
                <h1 class="text-white text-center mt-5">You Alredy In Account!</h1>
                <a id='btn-text' href="{% url "home" %}" class="nav-link text">To Home</a>
                <a id='btn-text' href="{% url "users:logout" %}" class="nav-link text text-logout">Logout</a>
                {% endblock content_ignore %}
                {% else %}
                <div class="card border-black border-2 shadow-lg bg-dark">
                    <div class="card-body">
                        <div id="log-image">
                            <img src="{% static "images/user64.png" %}" alt="">
                        </div>
                        <form method='POST'>
                            {% csrf_token %}
                            {% block content %}
                            <input type="text" name='' class='form-control my-3 py-2' placeholder='Username'>
                            {% endblock content %}
                        </form>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>