myreddit/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('subscriptions/', views.SubscriptionsView.as_view(), name='subscriptions'),
    path('all/', views.AllHomeView.as_view(), name='all_home'),
    
    path('search/', views.Search.as_view(), name='search'),
    
    path('post/<int:pk>/', views.ShowPost.as_view(), name='post'),
    path('post/create/', views.CreatePost.as_view(), name='add_post'),
    
    path('group/<int:pk>/', views.GroupView.as_view(), name='group'),
    path('group/create/', views.GroupCreateView.as_view(), name='create_group'),
    
    path('like_post/<int:pk>/', views.LikePostView, name='like_post'),
    path('like_comm/<int:pk>/', views.LikeCommView, name='like_comm'),
    
    path('group/join/<int:pk>/', views.JoinGroupView, name='join_group'),
    path('group/quit/<int:pk>/', views.QuitGroupView, name='quit_group'),
]

myreddit/myreddit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from myreddit import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myreddit/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    
    path('password-change/', views.PasswordChangeUser.as_view(), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneUser.as_view(), name='password_change_done'),
    
    path('password-reset/', views.PasswordResetUser.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneUser.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.PasswordResetConfirmUser.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', views.PasswordResetCompleteUser.as_view(), name='password_reset_complete'),
    
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<slug:slug>/', views.ProfileView.as_view(), name='profile'),
]

myreddit/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from myreddit.settings import DEFAULT_USER_IMAGE


class User(AbstractUser):
    avatar = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name='Фото', default=DEFAULT_USER_IMAGE)
    status = models.CharField(max_length=80, default='', blank=True, null=True, verbose_name='Статус')
    groups = models.ManyToManyField('main.Group', blank=True, related_name='groups', verbose_name='Группы')
    likes = models.ManyToManyField('main.Post', blank=True, related_name='liked', verbose_name='Лайки')
    
    def get_absolute_url(self):
        return reverse("users:profile", kwargs={'pk': self.id})

myreddit/users/forms.py
from typing import Any
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm


class RegisterUserForm(UserCreationForm):
    password1 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Password'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Confirm Password'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Username'}),
            'email': forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Last Name'}),
        }
        
class LoginUserForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Username / Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Password'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
    
class PasswordChangeUserForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Old Password'}))
    new_password1  = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'New Password'}))
    new_password2  = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Confirm Password'}))
    
    class Meta:
        model = get_user_model()
        field = ['old_password', 'new_password1', 'new_password2']

class PasswordResetUserForm(PasswordResetForm):
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Email'}))

class PasswordResetConfirmUserForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Password'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Confirm Password'}))
        
        
class UpdateUserForm(forms.ModelForm):
    avatar = forms.ImageField(required=False, label='Photo')
    username = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Username'}))
    status = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Status'}))
    email = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Email'}))
    first_name = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'class': 'form-control my-3 py-2', 'placeholder': 'Last Name'}))
    class Meta:
        model = get_user_model()
        fields = ['avatar', 'username', 'status', 'email', 'first_name', 'last_name']

myreddit/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.contrib.auth import logout, get_user_model
from .forms import  RegisterUserForm, LoginUserForm, PasswordChangeUserForm, PasswordResetUserForm, PasswordResetConfirmUserForm, UpdateUserForm
from main.utils import LoginMixn

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    extra_context = {'title': 'Register'}

class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('home')
    extra_context = {'title': 'Login'}
    
class PasswordChangeUser(PasswordChangeView):
    form_class = PasswordChangeUserForm
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('users:password_change_done')
    extra_context = {'title': 'Change Password'}

class PasswordChangeDoneUser(PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'
    extra_context = {'title': 'Congratulations'}

class PasswordResetUser(PasswordResetView):
    form_class = PasswordResetUserForm
    template_name='users/password_reset_form.html'
    email_template_name="users/password_reset_email.html"
    success_url=reverse_lazy('users:password_reset_done')
    extra_context = {'title': 'Reset Password By Email'}
    
class PasswordResetDoneUser(PasswordResetDoneView):
    template_name='users/password_reset_done.html'
    extra_context = {'title': 'Reset Password'}

class PasswordResetConfirmUser(PasswordResetConfirmView):
    form_class = PasswordResetConfirmUserForm
    template_name='users/password_reset_confirm.html'
    success_url=reverse_lazy('users:password_reset_complete')
    extra_context = {'title': 'Reset Password'}

class PasswordResetCompleteUser(PasswordResetCompleteView):
    template_name='users/password_reset_complete.html'
    extra_context = {'title': 'Congratulations'}
    
class ProfileView(LoginMixn, DetailView, UpdateView):
    template_name = 'users/profile.html'
    context_object_name = 'userp'
    form_class = UpdateUserForm
    
    def get_object(self, queryset = None):
        if field := self.kwargs.get(self.pk_url_kwarg):
            return get_object_or_404(get_user_model(), pk=field)
        elif field := self.kwargs.get(self.slug_url_kwarg):
            return get_object_or_404(get_user_model(), username=field)
    
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['title'] = context[self.context_object_name].username
        
        return context

myreddit/users/templates/users/login.html
{% extends "login_base.html" %}
{% block content %}
<div class="form-error text-white">{{ form.non_field_errors }}</div>

{% for f in form %}
{{ f }}
<div class="form-error text-white">{{ f.errors }}</div>
{% endfor %}

<div class="text-center mt-3">
    <button class="btn btn-success my-3">Login</button>
    <a id='btn-text' href="{% url "users:password_reset" %}" class="nav-link wx-auto">Forgot Password?</a>
    <a id='btn-text' href="{% url "users:register" %}" class="nav-link">Create Account</a>
</div>

{% endblock content %}

myreddit/users/templates/users/password_change.html
{% extends "login_base.html" %}

{% block content_ignore %}
<div class="form-error text-white">{{ form.non_field_errors }}</div>

{% for f in form %}
{{ f }}
<div class="form-error text-white">{{ f.errors }}</div>
{% endfor %}


<div class="text-center mt-3">
    <button class="btn btn-success my-3">Confirm</button>
</div>
<a id='btn-text' href="{% url "users:password_reset" %}" class="nav-link wx-auto">Forgot Password?</a>
{% endblock content_ignore %}

myreddit/users/templates/users/password_change_done.html
{% extends "login_base.html" %}
{% block content_ignore %}
<div class="form-error text-white">{{ form.non_field_errors }}</div>

<div class="text-center mt-3 text-white">
    <h3>You have successfully changed your password!</h3>
    <a href="{% url "home" %}" class="btn btn-success my-3">To Site</a>
</div>

{% endblock content_ignore %}

myreddit/users/templates/users/password_reset_complete.html
{% extends "login_base.html" %}

{% block content %}

<div class="text-center mt-3 text-white">
    <h3>You have successfully reset your password!</h3>
    <a href="{% url "users:login" %}" class="btn btn-success my-3">To Login</a>
</div>

{% endblock content %}

myreddit/users/templates/users/password_reset_confirm.html
{% extends "login_base.html" %}

{% block content %}
<div class="form-error text-white">{{ form.non_field_errors }}</div>

{% for f in form %}
{{ f }}
<div class="form-error text-white">{{ f.errors }}</div>
{% endfor %}


<div class="text-center mt-3">
    <button class="btn btn-success my-3">Save</button>
</div>

{% endblock content %}

myreddit/users/templates/users/password_reset_done.html
{% extends "login_base.html" %}

{% block content %}

<div class="text-center mt-3 text-white">
    <h5>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
    <br>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</h5>
    <a href="{% url "users:password_reset" %}" class="btn btn-success my-3">Back To Reset</a>
    <a href="{% url "home" %}" class="btn btn-success my-3">Back To Home</a>
</div>

{% endblock content %}

myreddit/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

myreddit/users/templates/users/password_reset_form.html
{% extends "login_base.html" %}

{% block content %}
<div class="form-error text-white">{{ form.non_field_errors }}</div>

{% for f in form %}
{{ f }}
<div class="form-error text-white">{{ f.errors }}</div>
{% endfor %}


<div class="text-center mt-3">
    <button class="btn btn-success my-3">Reset By E-mail</button>
</div>

{% endblock content %}

myreddit/users/templates/users/profile.html
{% extends "base.html" %}

{% block content %}

<div class="profile">
    <div class="profile-header">
        <div class='p-h-top'>
            <div class="profile-photo">
                <img src="{{ userp.avatar.url }}">
            </div>
            <span>{{ userp.username }}</span>
        </div>
        <div class='p-h-bottom'>
            <div class="profile-status">
                <span>
                    {% if userp.status %}
                    {{userp.status}}
                    {% else %}
                    ...
                    {% endif %}
                </span>
            </div>
        </div>
    </div>

    <div class="profile-main my-4">
        <div class="profile-main-header"> <!-- text-white bg-secondary border-0 -->
            <nav>
                <div class="nav nav-tabs py-2 my-2 border-secondary border-2" id="nav-tab" role="tablist">
                  <button class="nav-link active " id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="true">Profile</button>
                  <button class="nav-link" id="nav-posts-tab" data-bs-toggle="tab" data-bs-target="#nav-posts" type="button" role="tab" aria-controls="nav-posts" aria-selected="false">Posts</button>
                  <button class="nav-link" id="nav-groups-tab" data-bs-toggle="tab" data-bs-target="#nav-groups" type="button" role="tab" aria-controls="nav-groups" aria-selected="false">Groups</button>
                  <button class="nav-link" id="nav-comments-tab" data-bs-toggle="tab" data-bs-target="#nav-comments" type="button" role="tab" aria-controls="nav-comments" aria-selected="false">Comments</button>
                </div>
            </nav>
        </div>
        <div class="profile-content">
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">
                    {% include "users/includes/profile.html" %}
                </div>
                <div class="tab-pane fade" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab" tabindex="0">
                    {% for post in userp.post.all %}
                    {% include "main/includes/post.html" %}
                    {% endfor %}
                </div>
                <div class="tab-pane fade" id="nav-groups" role="tabpanel" aria-labelledby="nav-groups-tab" tabindex="0">
                    <div>
                        <span>Admin:</span>
                        {% for group in userp.group.all %}
                        {% include "users/includes/group.html" %}
                        {% endfor %}
                    </div>
                    <div>
                        <span>Member:</span>
                        {% for group in userp.member.all %}
                        {% include "users/includes/group.html" %}
                        {% endfor %}
                    </div>
                </div>
                <div class="tab-pane fade" id="nav-comments" role="tabpanel" aria-labelledby="nav-comments-tab" tabindex="0">
                    {% for comm in userp.comment.all %}
                    {% include "main/includes/comment.html" %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock content %}

myreddit/users/templates/users/register.html
{% extends "login_base.html" %}
{% block content %}
<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
{{ f }}
<div class="form-error text-white">{{ f.errors }}</div>
{% endfor %}


<div class="text-center mt-3">
    <button class="btn btn-success my-3">Register</button>
    <a id='btn-text' href="{% url "users:login" %}" class="nav-link text">Alredy Have An Account?</a>
</div>

{% endblock content %}